const CATEGORIES_FETCH_FAILED = 'category.CATEGORIES_FETCH_FAILED';
const CATEGORIES_FETCH_REQUESTED = 'category.CATEGORIES_FETCH_REQUESTED';
const CATEGORIES_FETCH_SUCCEEDED = 'category.CATEGORIES_FETCH_SUCCEEDED';


export {
    CATEGORIES_FETCH_FAILED,
    CATEGORIES_FETCH_REQUESTED,
    CATEGORIES_FETCH_SUCCEEDED
}