const PAYMENT_SOURCES_FETCH_FAILED = 'paymentSources.PAYMENT_SOURCES_FETCH_FAILED';
const PAYMENT_SOURCES_FETCH_REQUESTED = 'paymentSources.PAYMENT_SOURCES_FETCH_REQUESTED';
const PAYMENT_SOURCES_FETCH_SUCCEEDED = 'paymentSources.PAYMENT_SOURCES_FETCH_SUCCEEDED';


export {
    PAYMENT_SOURCES_FETCH_FAILED,
    PAYMENT_SOURCES_FETCH_REQUESTED,
    PAYMENT_SOURCES_FETCH_SUCCEEDED
}